### ISSUE TITLE
bmf format, what is it?

### ISSUE THREAD

**Issue by fedor-elizarov** [orangeduck/Corange#20]
I read code bmf_load_file  but i don`t understand it (
maybe you prompt me what is it? that the specification for him? ::)

**Comment by orangeduck** [comment]
Hi,

Its just a binary format that only Corange uses. Essentially it is a dump of all the raw binary data that goes into the opengl buffers. There isn't a spec but you can look at `bmf_save_file` to get an idea of how it works.

- Dan

**Comment by fedor-elizarov** [comment]
Thanks for the answer, I went to google about vbo and other :D . And thanks for the cool engine. This is a great project for the study of 3D graphics ::)

P.S. Sorry for my english 

- Dan

**Comment by gwald** [comment]
Hi,
Great little engine.. very impressive :+1: 
Just to expend on this question, what software/plugin/workflow/pipeline is recommended to get skl/bmf/ani ?

**Comment by orangeduck** [comment]
Hi @gwald,

Thanks!

`skl`/`ani` are just renamed `smd` files: https://developer.valvesoftware.com/wiki/Studiomdl_Data

There is a plugin for 3dsmax if I remember correctly.

`bmf` files will be automatically generated by Corange from `obj` and `smd` files which contain meshes so you can use those first.
