### ISSUE TITLE
Advice on animation blending

### ISSUE THREAD

**Issue by gwald** [orangeduck/Corange#22]
Hi Daniel,
I'm looking at extending Corange, I don't mind sharing/uploading my changes etc.
So I thought I would ask you first before I hack it horribly.

Just wondering if you can advise regarding adding animation blending, ie top and bottom biped animations.
I'm still new, but I know my way around, so just any general points would be helpful.

Cheers 
gwald

**Comment by orangeduck** [comment]
Hi,

As you probably guessed I'm not really maintaining Corange anymore but I will be happy to merge pull requests etc as long as they match the existing style or Corange and code is good quality.

The current animation system for Corange is pretty messy/basic but it has all the different operations for quaternions etc. You can probably get started by hacking on the `animated_object` entity.

- Dan

**Comment by gwald** [comment]
Thanks Dan,
I've hacked a character animation which has a top and bottom animation.
Not very elegant, but works, not sure if it's worth checking in, it's very basic.
It's here:
https://github.com/orangeduck/Corange/compare/master...gwald:master

This is how I use it:
https://github.com/gwald/my-corange-demo/blob/master/ANIMATED_CHAR%20example/CorangeSDL.c#L77

Cheers
Thanks again :+1:

**Comment by orangeduck** [comment]
Thanks - I'll take a look later but looks like a good start.

**Comment by gwald** [comment]
Disregard it really, it's not worth pulling
