### ISSUE TITLE
OpenGL Error: Invalid Enum (running rendering demo)

### ISSUE THREAD

**Issue by DogFive** [orangeduck/Corange#24]
I've been able to get some of the other demos to work but when I go to run the rendering demo I get the following output:

[DEBUG] (src/corange.c:corange_init:53) Starting Corange...
[DEBUG] (src/corange.c:corange_init:56) Creating Asset Manager...
[DEBUG] (src/corange.c:corange_init:57) Core Assets At '../../assets_core' ...
[DEBUG] (src/corange.c:corange_init:95) Creating Entity Manager...
[DEBUG] (src/corange.c:corange_init:110) Creating UI Manager...
[DEBUG] (src/corange.c:corange_init:127) Creating Graphics Manager...
OpenGL Info
Vendor: VMware, Inc.
Renderer: Gallium 0.4 on llvmpipe (LLVM 3.8, 256 bits)
Version: 3.0 Mesa 12.0.6
Shader Version: 1.30
_____

Extensions here
______
[DEBUG] (src/corange.c:corange_init:131) Creating Audio Manager...
[DEBUG] (src/corange.c:corange_init:135) Creating Joystick Manager...
[DEBUG] (src/cjoystick.c:joystick_init:16) Found 0 joysticks
[DEBUG] (src/corange.c:corange_init:139) Creating Network Manager...
[DEBUG] (src/corange.c:corange_init:142) Finished!
[DEBUG] (src/casset.c:folder_load:308) Loading Folder: '/home/<uname>/Dev/Corange-master/demos/rendering/assets/podium'
[DEBUG] (src/casset.c:file_load:282) Loading: '/home/<uname>/Dev/Corange-master/demos/rendering/assets/podium/podium.dds'
[ERROR] (src/assets/texture.c:dds_load_file:572) OpenGL Error: Invalid Enum

**Comment by gwald** [comment]
Hmm, haven't seen this problem before, have you tried looking at the config files, maybe not pointing to the right file (DDS)?
Maybe stepping through the code would help?

**Comment by orangeduck** [comment]
Also what platform are you running on? Since you are using Mesa I wonder if you actually have a version of OpenGL that supports DDS textures.

**Comment by gwald** [comment]
yeah, looks like it's VMWare, could be a driver issue.
Strange if the other demo's worked :/
